using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        // Heroine datas
        [SerializeField] public string HeroineName;
        [SerializeField] public int Favorability = 0;
        [SerializeField] public int Emotion = 0;
        [SerializeField] public int Hungry = 0;
        //turn main procces
        [SerializeField] public int Violet = 0;
        [SerializeField] public int Target_Violet = 1000;
        [SerializeField] public int Deadline = 14;
        [SerializeField] public int ActionPoint = 9;
        [SerializeField] public int Turn = 1;
        [SerializeField] public int Clean = 80;
        [SerializeField] public int Money = 500;
        [SerializeField] public int Contribution = 0;

        [SerializeField] public int Days = 1;

        [SerializeField] public List<EventData> eventDatas = new List<EventData>();
        [SerializeField] public string screenPath = "";
        [SerializeField] public string saveDate = "";
        [SerializeField] public string flowchartName = "";
        [SerializeField] public string saveScene = "";
        [SerializeField] public string blockName = "";
    }

    [System.Serializable]
    public class EventData
    {
        [SerializeField] public string eventType = "";
        [SerializeField] public List<string> datas = new List<string>();
    }
}